using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SearchBarMVVM.Services.DataStore
{
    public static class DataStoreService
    {
        public static List<string> Sports { get; } = new List<string>
        {
            "Ala delta",
            "Acrobacia",
            "Acuatlón",
            "Aeróbic",
            "Alpinismo",
            "Artes marciales",
            "Atletismo",
            "Automobilismo",
            "Baloncesto",
            "Balonmano",
            "Billar",
            "Billarda",
            "Birlos",
            "Bobsleigh",
            "Bodyboard",
            "Boxeo",
            "Bádminton",
            "Béisbol",
            "Caza",
            "Ciclismo",
            "Colombofilia",
            "Corfebol",
            "Críquet",
            "Cróquet",
            "Cuadratlón",
            "Curling",
            "Danza deportiva",
            "Dardos",
            "Esgrima",
            "Espeleoloxía",
            "Esquí",
            "Equitación",
            "Fútbol",
            "Fútbol playa",
            "Fútbol sala",
            "Golf",
            "Gimnasia",
            "Gimnasia rítmica",
            "Halterofilia",
            "Hípica",
            "Hóckey sobre patínes",
            "Hóckey sobre hierba",
            "Hóckey sobre hielo",
            "Hóckey",
            "Hurling",
            "Judo",
            "Karate",
            "Kendo",
            "Kickboxing",
            "Karting",
            "Kung Fu",
            "Lacrosse",
            "Lucha",
            "Lucha tradicional gallega",
            "Luciadas extremas",
            "Sumerjo",
            "Motociclismo",
            "Motonáutica",
            "Mountainbike",
            "Mhuai Thay",
            "Natación",
            "Octopush",
            "Orientación",
            "Paracaidismo",
            "Parapente",
            "Parkour",
            "Patinaxe",
            "Paintball",
            "Pelota",
            "Pilota valenciana",
            "Pelota vasca",
            "Pentatlón moderno",
            "Pesca deportiva",
            "Petanca",
            "Piragüismo",
            "Polo",
            "Remo",
            "Rugby",
            "Salto de trampolín",
            "Senderismo",
            "Softbol",
            "Shinty",
            "Skateboard",
            "Skeleton",
            "Snowboard",
            "Speedball",
            "Squash",
            "Sumo",
            "Superbikes",
            "Surf",
            "Tenis",
            "Tenis de mesa",
            "Tiro",
            "Tiro con arco",
            "Triatlón",
            "Taekwondo",
            "Ultralixeiros",
            "Vela",
            "Voleibol",
            "Volei playa",
            "Valetudo",
            "Waterpolo",
            "Windsurf",
            "Wushu",
            "Win Tsun2",
            "Xadrez",
            "Ximnasia",
            "Ximnasia rítmica"
        };

        public static List<string> GetSearchResults(string queryString)
        {
            var normalizedQuery = queryString?.ToLower() ?? "";
            return Sports.Where(f => f.ToLowerInvariant().Contains(normalizedQuery)).ToList();
        }
    }
}
